#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

myvar=1
while [ $myvar -le 10 ]
do
       	echo "Best School"
	if [ $myvar -eq 9 ]
	then
		echo "Hi"
	fi
       	(( myvar++ ))
done
