#!/usr/bin/env bash
# This script is displaying "bad luck" for the 4th loop iteration, ""good luck"  for the 8th loop iteration and "Best School" for the other iterations.

myvar=1
while [ $myvar -le 10 ]
do
	if [ $myvar -eq 4 ]
	then
		echo "bad luck"
	elif [ $myvar -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( myvar++ ))
done
