#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.
# Display hours from 0 to 12
# Display minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		(( min++ ))
	done
	(( hour++ ))
done
